# Generated by Django 4.1.7 on 2023-08-21 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='user_chat',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='user_name',
        ),
    ]
