# Generated by Django 4.1.7 on 2023-08-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reminders', '0002_remove_siteuser_user_chat_remove_siteuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='user_chat',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
