# Generated by Django 4.1.7 on 2023-10-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reminders', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
