# Generated by Django 4.1.7 on 2023-10-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reminders', '0007_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='user_chat',
            field=models.PositiveIntegerField(max_length=10, unique=True),
        ),
    ]
