# Generated by Django 4.1.7 on 2023-08-21 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='birthday_boy',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.day'),
        ),
        migrations.AddField(
            model_name='birthday_boy',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.month'),
        ),
        migrations.AddField(
            model_name='birthday_boy',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
