# Generated by Django 4.1.7 on 2023-04-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_alter_month_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32)),
                ('user_chat', models.IntegerField(unique=True)),
                ('Birthday_boy', models.ManyToManyField(to='reminders.birthday_boy')),
            ],
        ),
    ]
