# Generated by Django 4.1.7 on 2023-04-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Birthday_boy',
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.ManyToManyField(to='reminders.birthday_boy'),
        ),
    ]
