# Generated by Django 4.1.7 on 2023-04-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0004_remove_user_birthday_boy_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
        migrations.AddField(
            model_name='birthday_boy',
            name='user',
            field=models.ManyToManyField(to='reminders.user'),
        ),
    ]
