# Generated by Django 4.1.7 on 2023-04-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_remove_user_user_birthday_boy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday_boy',
            name='surname',
            field=models.CharField(max_length=32),
        ),
    ]
